# Generated by Django 3.2.13 on 2023-09-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_stripe_product_price_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products_images"),
        ),
    ]
